version: "3.8"

services:
    maki-cata-blog:
        image: chocalata/maki.catalin-trandafir.com:maki-cata-blog_2024-12-21-v1
        ports:
            - 3000:3000
        env_file:
            - .env
        networks:
            - maki-cata-network
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.maki_catalin-trandafir_com.entrypoints=web, websecure"
            - "traefik.http.routers.maki_catalin-trandafir_com.rule=Host(`maki.catalin-trandafir.com`) || Host(`www.maki.catalin-trandafir.com`)"
            - "traefik.http.routers.maki_catalin-trandafir_com.tls=true"
            - "traefik.http.routers.maki_catalin-trandafir_com.tls.certresolver=production"
            - "traefik.http.services.maki_catalin-trandafir_com.loadbalancer.server.port=3000"
            - "traefik.docker.network=traefik"
    maki-cata-db:
        image: chocalata/maki.catalin-trandafir.com:maki-cata-db_2024-12-21-v4
        volumes:
            - maki-cata-db:/data/db
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USER}
            MYSQL_DATABASE: ${DB_NAME}
        networks:
            - maki-cata-network

volumes:
    maki-cata-db:

networks:
    maki-cata-network:
    traefik:
        external:
            name: traefik
